services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
  
  python:
    build: ./python
    ports:
      - "8000:5000"
    env_file:
      - .env

  database:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  studio:
    build:
      context: ./frontend
      target: builder
    working_dir: /app
    command: npx prisma studio --port 5555 --hostname 0.0.0.0
    ports:
      - "5555:5555"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
  
  storage:
    image: minio/minio
    build: ./storage
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    environment:
      MINIO_CONSOLE_ADDRESS: ":9001"
    volumes:
      - miniodata:/data
    command: server /data

networks: 
  prisma-network:

volumes:
  pgdata:
  miniodata: